import type { Flavor, FlavorAllergens, FlavorId, VinculoId } from '@/types';

// ════════ FLAVOR DATA ════════
export const FLAVORS: Record<FlavorId, Flavor> = {
  fresa: {
    cls: 'th-fresa', c: 'var(--rose)', c2: 'var(--rose2)',
    name: 'Frambesa y Fresa', persona: 'La Corazón Abierto',
    desc: 'Apasionado/a, empático/a y completamente presente. Sientes profundo y amas sin medias tintas.',
    ins: {
      tag: 'TU ESENCIA',
      text: 'Traes calidez de forma natural, sin esfuerzo consciente. Tu intensidad emocional no es un exceso — es profundidad de presencia real.',
      hl: 'Sientes profundo porque estás completamente vivo/a.',
    },
    psych: 'La psicología positiva de Fredrickson demuestra que las emociones intensas amplían el repertorio de acción. Tu empatía elevada correlaciona con mayor conexión auténtica.',
    traits: [
      { l: 'INTENSIDAD', v: 'Muy alta' },
      { l: 'EMPATÍA', v: 'Profunda' },
      { l: 'ENERGÍA', v: 'Cálida' },
      { l: 'CONEXIÓN', v: 'Intensa' },
    ],
    tips: [
      { t: '<strong>Practica recibir</strong> con la misma naturalidad con que das.' },
      { t: '<strong>Date tiempo para procesar</strong> tras experiencias muy emotivas.' },
      { t: '<strong>Escribe lo que sientes</strong> antes de comunicarlo.' },
      { t: '<strong>Aprende a decir que no</strong> sin culpa.' },
    ],
    base: {
      rec: 'Leche entera', recD: 'Potencia la cremosidad y el dulzor natural.',
      alt: 'Leche vegetal', altD: 'Avena o coco como alternativa sin lactosa.',
    },
    allergens: { lacteos: true, gluten: false, huevo: false, frutosSecs: false, soja: false, sulfitos: true },
    allergenNotes: { lacteos: 'Contiene leche', sulfitos: 'En frambesas procesadas' },
    baseType: 'leche',
    maridaje: ['Espresso doble', 'Agua con gas y lima'],
  },
  vainilla: {
    cls: 'th-vainilla', c: 'var(--gold)', c2: 'var(--gold2)',
    name: 'Vainilla y Coco', persona: 'El Alma Serena',
    desc: 'Clásico/a pero nunca predecible. Tu presencia tiene un efecto regulador sobre quienes te rodean.',
    ins: {
      tag: 'TU ESENCIA',
      text: 'La vainilla es el sabor más complejo de la naturaleza pese a ser percibida como simple. Igual que tú.',
      hl: 'Tu calma no es indiferencia. Es fortaleza bien sostenida.',
    },
    psych: 'La psicología del apego describe tu perfil como estilo seguro: puedes mantener intimidad sin perder tu centro. (John Bowlby)',
    traits: [
      { l: 'ESTABILIDAD', v: 'Alta' },
      { l: 'APEGO', v: 'Seguro' },
      { l: 'RITMO', v: 'Pausado' },
      { l: 'PROFUNDIDAD', v: 'Rica' },
    ],
    tips: [
      { t: '<strong>Permítete sentir</strong> sin buscar la calma de inmediato.' },
      { t: '<strong>Comparte más de lo que piensas.</strong>' },
      { t: '<strong>Introduce novedad gradual.</strong>' },
      { t: '<strong>Expresa tu afecto en palabras.</strong>' },
    ],
    base: {
      rec: 'Agua', recD: 'Resalta la pureza de la vainilla y la frescura del coco.',
      alt: 'Leche entera', altD: 'Opción más cremosa.',
    },
    allergens: { lacteos: false, gluten: false, huevo: false, frutosSecs: true, soja: false, sulfitos: false },
    allergenNotes: { frutosSecs: 'Coco' },
    baseType: 'agua',
    maridaje: ['Café de olla', 'Té chai caliente'],
  },
  menta: {
    cls: 'th-menta', c: 'var(--mint)', c2: 'var(--mint2)',
    name: 'Menta y Lima', persona: 'La Mente Brillante',
    desc: 'Refrescante, rápido/a y con algo interesante que aportar siempre. Tu mente no se detiene — y eso es una ventaja.',
    ins: {
      tag: 'TU ESENCIA',
      text: 'La menta despierta los sentidos. Tú haces lo mismo en los entornos donde participas.',
      hl: 'Tu mente, bien descansada, puede con todo.',
    },
    psych: 'El modelo de los Cinco Grandes te ubica con puntuaciones altas en Apertura a la Experiencia. Adam Grant llama a esto "pensamiento generativo".',
    traits: [
      { l: 'CURIOSIDAD', v: 'Muy alta' },
      { l: 'APERTURA', v: 'Máxima' },
      { l: 'RITMO', v: 'Rápido' },
      { l: 'CREATIVIDAD', v: 'Activa' },
    ],
    tips: [
      { t: '<strong>Practica el silencio mental deliberado.</strong>' },
      { t: '<strong>Date espacio para sentir</strong> sin analizar.' },
      { t: '<strong>Termina lo que empiezas.</strong>' },
      { t: '<strong>Cuida tu cuerpo</strong> con la misma atención que tu mente.' },
    ],
    base: {
      rec: 'Agua', recD: 'Potencia la frescura de la menta y la acidez de la lima.',
      alt: 'Solo agua', altD: 'Diseñado para base de agua.',
    },
    allergens: { lacteos: false, gluten: false, huevo: false, frutosSecs: false, soja: false, sulfitos: false },
    allergenNotes: {},
    baseType: 'agua',
    maridaje: ['Agua mineral fría', 'Té verde con hielo'],
  },
  choco: {
    cls: 'th-choco', c: 'var(--mocha)', c2: 'var(--mocha2)',
    name: 'Chocolate y Café', persona: 'La Profundidad Elegante',
    desc: 'Complejo/a, intenso/a y con capas que pocos llegan a conocer. Tienes un mundo interior extraordinariamente rico.',
    ins: {
      tag: 'TU ESENCIA',
      text: 'El chocolate es el sabor más parecido a las emociones humanas: amargo, dulce, profundo. Igual que tú.',
      hl: 'Tu profundidad no es complicación. Es riqueza.',
    },
    psych: 'La psicología Junguiana reconoce en ti una vida interior muy desarrollada: alta introspección y habilidad para sostener paradojas emocionales.',
    traits: [
      { l: 'VIDA INTERIOR', v: 'Muy rica' },
      { l: 'INTROSPECCIÓN', v: 'Natural' },
      { l: 'INTENSIDAD', v: 'Controlada' },
      { l: 'MADUREZ', v: 'Emocional' },
    ],
    tips: [
      { t: '<strong>Busca momentos de ligereza</strong> deliberada.' },
      { t: '<strong>Comparte tu mundo interior</strong> con alguien de confianza.' },
      { t: '<strong>Celebra lo cotidiano.</strong>' },
      { t: '<strong>Permítete ser cuidado/a.</strong>' },
    ],
    base: {
      rec: 'Leche entera', recD: 'Potencia los aromas del cacao y suaviza el café.',
      alt: 'Leche de avena', altD: 'La avena complementa el chocolate sin dominar.',
    },
    allergens: { lacteos: true, gluten: false, huevo: false, frutosSecs: false, soja: false, sulfitos: false },
    allergenNotes: { lacteos: 'Leche entera en base.' },
    baseType: 'leche',
    maridaje: ['Café negro', 'Mezcal añejo'],
  },
  mango: {
    cls: 'th-mango', c: 'var(--peach)', c2: 'var(--peach2)',
    name: 'Mango y Maracuyá', persona: 'La Energía Solar',
    desc: 'Vibrante, espontáneo/a y con una energía que llena los espacios. Amas la vida de forma genuina.',
    ins: {
      tag: 'TU ESENCIA',
      text: 'El mango es el sabor de la alegría sin disculpas. Tú te permites disfrutar sin necesitar justificación.',
      hl: 'Tu alegría no es superficial. Es una elección valiente.',
    },
    psych: 'Martin Seligman identificaría en ti fortalezas como vitalidad, entusiasmo y esperanza — predictores robustos de resiliencia.',
    traits: [
      { l: 'VITALIDAD', v: 'Alta' },
      { l: 'ESPONTANEIDAD', v: 'Natural' },
      { l: 'ALEGRÍA', v: 'Genuina' },
      { l: 'RESILIENCIA', v: 'Rápida' },
    ],
    tips: [
      { t: '<strong>Cultiva la quietud deliberada.</strong>' },
      { t: '<strong>Aprende a estar con emociones difíciles.</strong>' },
      { t: '<strong>Pon tus metas por escrito.</strong>' },
      { t: '<strong>Profundiza en relaciones</strong> más allá de los buenos momentos.' },
    ],
    base: {
      rec: 'Agua', recD: 'Resalta la acidez tropical del mango y la maracuyá.',
      alt: 'Leche de coco', altD: 'Suma cremosidad tropical.',
    },
    allergens: { lacteos: false, gluten: false, huevo: false, frutosSecs: false, soja: false, sulfitos: false },
    allergenNotes: {},
    baseType: 'agua',
    maridaje: ['Agua de jamaica', 'Kombucha de jengibre'],
  },
  lavanda: {
    cls: 'th-lavanda', c: 'var(--lav)', c2: 'var(--lav2)',
    name: 'Lavanda y Arándano', persona: 'La Sensibilidad Creativa',
    desc: 'Soñador/a, sensible e intuitivo/a. Percibes dimensiones que otros pasan por alto. Tienes una relación privilegiada con el arte.',
    ins: {
      tag: 'TU ESENCIA',
      text: 'La lavanda calma y eleva al mismo tiempo. Haces que otros se sientan vistos con un esfuerzo mínimo.',
      hl: 'Tu sensibilidad no es debilidad. Es inteligencia.',
    },
    psych: 'Elaine Aron acuñó el término Persona Altamente Sensible (PAS) para tu perfil: procesamiento profundo, empatía aguda y reactividad estética elevada.',
    traits: [
      { l: 'SENSIBILIDAD', v: 'Alta (PAS)' },
      { l: 'INTUICIÓN', v: 'Aguda' },
      { l: 'CREATIVIDAD', v: 'Natural' },
      { l: 'ESTÉTICA', v: 'Elevada' },
    ],
    tips: [
      { t: '<strong>Protege tu energía</strong> de forma consciente.' },
      { t: '<strong>Pon límites sin culpa.</strong>' },
      { t: '<strong>Confía en tu intuición.</strong>' },
      { t: '<strong>Comparte lo que creas.</strong>' },
    ],
    base: {
      rec: 'Agua o leche', recD: 'En agua: más floral. En leche: más cremoso.',
      alt: 'Leche de almendra', altD: 'La almendra complementa la lavanda con elegancia.',
    },
    allergens: { lacteos: false, gluten: false, huevo: false, frutosSecs: true, soja: false, sulfitos: false },
    allergenNotes: { frutosSecs: 'Almendra si se usa como base.' },
    baseType: 'ambas',
    maridaje: ['Té de camomila', 'Agua floral de rosas'],
  },
  matcha: {
    cls: 'th-matcha', c: 'var(--teal)', c2: 'var(--teal2)',
    name: 'Matcha y Pistache', persona: 'La Mente Consciente',
    desc: 'Buscas el equilibrio entre la disciplina y el placer. Tienes la rara capacidad de ser riguroso/a sin perder la sensorialidad.',
    ins: {
      tag: 'TU ESENCIA',
      text: 'El matcha requiere preparación cuidadosa para revelar su mejor versión. Tú funcionas igual: tu profundidad emerge cuando hay intención.',
      hl: 'Tu disciplina no es restricción. Es la forma en que te respetas.',
    },
    psych: 'La psicología del autocontrol de Roy Baumeister: alta autorregulación que, equilibrada con disfrute consciente, produce bienestar sostenido.',
    traits: [
      { l: 'AUTODISCIPLINA', v: 'Alta' },
      { l: 'CONSCIENCIA', v: 'Muy presente' },
      { l: 'EQUILIBRIO', v: 'Buscado' },
      { l: 'PLACER', v: 'Merecido' },
    ],
    tips: [
      { t: '<strong>Permite el desorden ocasional.</strong>' },
      { t: '<strong>Celebra los logros sin condiciones.</strong>' },
      { t: '<strong>Comparte tu proceso,</strong> no solo tus resultados.' },
      { t: '<strong>Practica el placer sin propósito.</strong>' },
    ],
    base: {
      rec: 'Leche de almendra', recD: 'La almendra realza los matices herbales del matcha y el pistache.',
      alt: 'Leche de avena', altD: 'La avena da cuerpo sin restar elegancia.',
    },
    allergens: { lacteos: false, gluten: false, huevo: false, frutosSecs: true, soja: false, sulfitos: false },
    allergenNotes: { frutosSecs: 'Pistache y almendra' },
    baseType: 'leche',
    maridaje: ['Agua de coco', 'Té verde ceremonial'],
  },
  miel: {
    cls: 'th-miel', c: 'var(--amber)', c2: 'var(--amber2)',
    name: 'Miel y Jengibre', persona: 'La Calidez Reparadora',
    desc: 'Eres el refugio de los demás en momentos de crisis. Tu capacidad de sostener a otros no es sacrificio — es vocación.',
    ins: {
      tag: 'TU ESENCIA',
      text: 'La miel cura. El jengibre activa. Tú combinas eso: la ternura que reconforta y la fuerza que mueve.',
      hl: 'Cuidas porque puedes. Ahora aprende a dejar que te cuiden a ti.',
    },
    psych: 'La psicología del cuidado estudia tu perfil. Kristin Neff demuestra que la autocompasión es requisito, no lujo.',
    traits: [
      { l: 'EMPATÍA', v: 'Muy alta' },
      { l: 'CUIDADO', v: 'Vocacional' },
      { l: 'CALIDEZ', v: 'Natural' },
      { l: 'FORTALEZA', v: 'Silenciosa' },
    ],
    tips: [
      { t: '<strong>Practica recibir ayuda</strong> sin convertirla en deuda.' },
      { t: '<strong>Pon límites desde el amor,</strong> no desde el agotamiento.' },
      { t: '<strong>Date a ti mismo/a</strong> la misma atención que das.' },
      { t: '<strong>Identifica quién te cuida a ti.</strong>' },
    ],
    base: {
      rec: 'Agua', recD: 'Resalta la miel y la intensidad del jengibre.',
      alt: 'Leche entera', altD: 'Con leche la miel se vuelve más reconfortante.',
    },
    allergens: { lacteos: false, gluten: false, huevo: false, frutosSecs: false, soja: false, sulfitos: false },
    allergenNotes: {},
    baseType: 'agua',
    maridaje: ['Té de canela', 'Agua tibia con limón'],
  },
  higo: {
    cls: 'th-higo', c: 'var(--fig)', c2: 'var(--fig2)',
    name: 'Higo y Queso Crema', persona: 'La Tradición Evolucionada',
    desc: 'Valoras profundamente tus raíces pero no temes reinventarte. Arraigo e innovación — una combinación poco común.',
    ins: {
      tag: 'TU ESENCIA',
      text: 'El higo es uno de los sabores más antiguos. El queso crema es contemporáneo. Tú eres exactamente esa combinación.',
      hl: 'Honras lo que vino antes sin quedar atrapado/a en ello.',
    },
    psych: 'Erik Erikson describiría tu perfil como alta integridad del ego: capacidad de honrar el pasado sin que este limite el presente.',
    traits: [
      { l: 'ARRAIGO', v: 'Profundo' },
      { l: 'ADAPTACIÓN', v: 'Activa' },
      { l: 'LEALTAD', v: 'Selectiva' },
      { l: 'EVOLUCIÓN', v: 'Intencional' },
    ],
    tips: [
      { t: '<strong>Distingue lo que vale conservar</strong> de lo que conservas por miedo.' },
      { t: '<strong>Permite que tu identidad evolucione.</strong>' },
      { t: '<strong>Comparte tu historia.</strong>' },
      { t: '<strong>Date permiso de innovar.</strong>' },
    ],
    base: {
      rec: 'Leche entera', recD: 'Potencia la textura del queso crema y la dulzura del higo.',
      alt: 'Leche de avena', altD: 'Cremosidad sin lactosa.',
    },
    allergens: { lacteos: true, gluten: false, huevo: false, frutosSecs: false, soja: false, sulfitos: false },
    allergenNotes: { lacteos: 'Queso crema — contiene lácteos.' },
    baseType: 'leche',
    maridaje: ['Vino blanco seco', 'Café de filtro'],
  },
  caramelo: {
    cls: 'th-caramelo', c: 'var(--caramel)', c2: 'var(--caramel2)',
    name: 'Caramelo Salado', persona: 'La Dualidad Dinámica',
    desc: 'Navegas con éxito entre tus contradicciones. Puedes ser dulce y directo/a, suave y firme. Esa dualidad es sofisticación real.',
    ins: {
      tag: 'TU ESENCIA',
      text: 'El caramelo salado fue revolucionario porque nadie creía que lo dulce y lo salado podían coexistir con elegancia. Tú vives esa verdad.',
      hl: 'No tienes que elegir quién ser. Puedes ser todo eso a la vez.',
    },
    psych: 'La psicología de la complejidad del yo (Patricia Linville) muestra que personas con identidades multifacéticas tienen mayor resiliencia emocional.',
    traits: [
      { l: 'COMPLEJIDAD', v: 'Alta' },
      { l: 'ADAPTABILIDAD', v: 'Natural' },
      { l: 'AUTENTICIDAD', v: 'Multifaceta' },
      { l: 'RESILIENCIA', v: 'Robusta' },
    ],
    tips: [
      { t: '<strong>Abraza tus contradicciones.</strong>' },
      { t: '<strong>Comunica tus distintas facetas.</strong>' },
      { t: '<strong>Cuida no usar la adaptabilidad como máscara.</strong>' },
      { t: '<strong>Celebra la complejidad.</strong>' },
    ],
    base: {
      rec: 'Leche entera', recD: 'Equilibra lo dulce del caramelo y realza el contrapunto salado.',
      alt: 'Leche de coco', altD: 'El coco agrega un toque tropical inesperadamente bueno.',
    },
    allergens: { lacteos: true, gluten: false, huevo: false, frutosSecs: false, soja: false, sulfitos: false },
    allergenNotes: { lacteos: 'Base de leche entera.' },
    baseType: 'leche',
    maridaje: ['Cappuccino', 'Sidra natural'],
  },
  yuzu: {
    cls: 'th-yuzu', c: 'var(--yuzu)', c2: 'var(--yuzu2)',
    name: 'Yuzu y Albahaca', persona: 'El Espíritu Eléctrico',
    desc: 'Tu energía es contagiosa, disruptiva y puramente original. No encajas en categorías fáciles — y ya dejaste de intentarlo.',
    ins: {
      tag: 'TU ESENCIA',
      text: 'El yuzu no se parece a ningún otro cítrico. Tú tienes esa misma singularidad que no puede imitarse.',
      hl: 'Tu originalidad no es performance. Es simplemente cómo eres.',
    },
    psych: 'Mihaly Csikszentmihalyi identificaría en ti alta creatividad intrínseca: orientación natural hacia la novedad y la ruptura de patrones.',
    traits: [
      { l: 'ORIGINALIDAD', v: 'Radical' },
      { l: 'DISRUPCIÓN', v: 'Natural' },
      { l: 'ENERGÍA', v: 'Eléctrica' },
      { l: 'SINGULARIDAD', v: 'Innegable' },
    ],
    tips: [
      { t: '<strong>Encuentra entornos que te permitan ser disruptivo/a.</strong>' },
      { t: '<strong>Aprende a aterrizar tus ideas.</strong>' },
      { t: '<strong>Cuida tu energía.</strong>' },
      { t: '<strong>Conecta con personas igualmente originales.</strong>' },
    ],
    base: {
      rec: 'Agua', recD: 'Permite que el yuzu y la albahaca brillen.',
      alt: 'Leche de coco', altD: 'El coco suaviza la intensidad.',
    },
    allergens: { lacteos: false, gluten: false, huevo: false, frutosSecs: false, soja: false, sulfitos: false },
    allergenNotes: {},
    baseType: 'agua',
    maridaje: ['Agua tónica', 'Té cítrico frío'],
  },
  earl: {
    cls: 'th-earl', c: 'var(--earl)', c2: 'var(--earl2)',
    name: 'Té Earl Grey y Limón', persona: 'La Serenidad Intelectual',
    desc: 'Encuentras la belleza en el orden y el pensamiento crítico. Tu mente trabaja con precisión.',
    ins: {
      tag: 'TU ESENCIA',
      text: 'El Earl Grey es sofisticado, no ostentoso. Tú tienes esa misma cualidad: presencia que se nota sin imponerse.',
      hl: 'Tu inteligencia no necesita demostrarse. Se siente.',
    },
    psych: 'La psicología cognitiva describe tu perfil como alto estilo reflexivo: procesas con profundidad antes de emitir juicio.',
    traits: [
      { l: 'PENSAMIENTO', v: 'Crítico y fino' },
      { l: 'ESTÉTICA', v: 'Del orden' },
      { l: 'SERENIDAD', v: 'Intelectual' },
      { l: 'PRECISIÓN', v: 'Natural' },
    ],
    tips: [
      { t: '<strong>Practica la imprecisión deliberada.</strong>' },
      { t: '<strong>Comunica con más calidez.</strong>' },
      { t: '<strong>Permite que te sorprendan.</strong>' },
      { t: '<strong>Busca espacios donde tu precisión sea valorada.</strong>' },
    ],
    base: {
      rec: 'Leche de avena', recD: 'La avena complementa los taninos del té con cremosidad contemporánea.',
      alt: 'Leche entera', altD: 'Da más cuerpo al perfil del Earl Grey.',
    },
    allergens: { lacteos: false, gluten: false, huevo: false, frutosSecs: false, soja: false, sulfitos: false },
    allergenNotes: {},
    baseType: 'leche',
    maridaje: ['Earl Grey caliente', 'Agua mineral con ralladura'],
  },
  chai: {
    cls: 'th-chai', c: 'var(--chai)', c2: 'var(--chai2)',
    name: 'Chai y Canela', persona: 'El Alma Especiada',
    desc: 'Posees una sabiduría antigua y una hospitalidad natural. Haces que los demás se sientan bienvenidos sin esfuerzo.',
    ins: {
      tag: 'TU ESENCIA',
      text: 'El chai es una mezcla de sabores que por separado podrían ser demasiado — juntos crean algo perfectamente armonioso. Igual que tú.',
      hl: 'Tu sabiduría no vino de libros. Vino de vivir y prestar mucha atención.',
    },
    psych: 'La psicología de la sabiduría (Monika Ardelt) describe tres dimensiones: cognitiva, reflexiva y afectiva. Tu perfil integra las tres.',
    traits: [
      { l: 'SABIDURÍA', v: 'Vivida' },
      { l: 'HOSPITALIDAD', v: 'Natural' },
      { l: 'CALIDEZ', v: 'Especiada' },
      { l: 'MEMORIA', v: 'Afectiva' },
    ],
    tips: [
      { t: '<strong>Comparte tu sabiduría con intención.</strong>' },
      { t: '<strong>Renueva tus perspectivas.</strong>' },
      { t: '<strong>Cuida no dar más de lo que tienes.</strong>' },
      { t: '<strong>Honra tu historia.</strong>' },
    ],
    base: {
      rec: 'Leche entera', recD: 'Potencia la intensidad de las especias. Envolvente.',
      alt: 'Leche de coco', altD: 'El coco agrega un toque exótico.',
    },
    allergens: { lacteos: true, gluten: false, huevo: false, frutosSecs: false, soja: false, sulfitos: false },
    allergenNotes: { lacteos: 'Base de leche entera.' },
    baseType: 'leche',
    maridaje: ['Chai latte', 'Café con especias'],
  },
  platano: {
    cls: 'th-platano', c: 'var(--platano)', c2: 'var(--platano2)',
    name: 'Plátano y Nuez Pecana', persona: 'El Confort Nostálgico',
    desc: 'Tu fortaleza reside en tus recuerdos y en la lealtad. Eres de los que no olvidan — ni los cumpleaños, ni las conversaciones, ni las promesas.',
    ins: {
      tag: 'TU ESENCIA',
      text: 'El plátano es el sabor de la infancia en muchas culturas. La nuez pecana agrega profundidad a lo que de otro modo sería solo dulzura.',
      hl: 'Tu memoria afectiva no es nostalgia. Es tu forma de no perder lo que importa.',
    },
    psych: 'La psicología de la nostalgia (Constantine Sedikides) muestra que el acceso sano a recuerdos positivos es un recurso de resiliencia real.',
    traits: [
      { l: 'LEALTAD', v: 'Profunda' },
      { l: 'MEMORIA', v: 'Afectiva' },
      { l: 'CONFORT', v: 'Generoso' },
      { l: 'ARRAIGO', v: 'Emocional' },
    ],
    tips: [
      { t: '<strong>Permite que el presente sea tan rico como el pasado.</strong>' },
      { t: '<strong>Aplica tu lealtad con discernimiento.</strong>' },
      { t: '<strong>Crea nuevos recuerdos activamente.</strong>' },
      { t: '<strong>Suelta lo que ya cumplió su propósito.</strong>' },
    ],
    base: {
      rec: 'Leche entera', recD: 'Potencia la cremosidad del plátano y la textura de la nuez.',
      alt: 'Leche de avena', altD: 'Cremosidad sin lactosa.',
    },
    allergens: { lacteos: true, gluten: false, huevo: false, frutosSecs: true, soja: false, sulfitos: false },
    allergenNotes: { lacteos: 'Base de leche entera.', frutosSecs: 'Nuez pecana — alérgeno principal.' },
    baseType: 'leche',
    maridaje: ['Leche con chocolate', 'Café con leche'],
  },
  vino: {
    cls: 'th-vino', c: 'var(--vino)', c2: 'var(--vino2)',
    name: 'Vino Tinto y Frutos Negros', persona: 'La Pasión Madura',
    desc: 'Vives con una intensidad refinada y gran profundidad. Has vivido suficiente para saber que la pasión y la madurez no se contradicen.',
    ins: {
      tag: 'TU ESENCIA',
      text: 'El vino bueno mejora con el tiempo. Tú eres exactamente eso — una persona que ha madurado sin perder su fuego.',
      hl: 'Tu intensidad tiene raíces. Por eso no se confunde con impulsividad.',
    },
    psych: 'La psicología del desarrollo adulto (Daniel Levinson) describe esta etapa como "individuación madura": integración de la pasión y la sabiduría.',
    traits: [
      { l: 'INTENSIDAD', v: 'Refinada' },
      { l: 'PROFUNDIDAD', v: 'Con historia' },
      { l: 'PASIÓN', v: 'Madura' },
      { l: 'COMPLEJIDAD', v: 'Vivida' },
    ],
    tips: [
      { t: '<strong>Comparte tu historia sin miedo.</strong>' },
      { t: '<strong>Permite la ligereza.</strong>' },
      { t: '<strong>Reconoce lo que te apasiona hoy.</strong>' },
      { t: '<strong>Cuida el autocuidado.</strong>' },
    ],
    base: {
      rec: 'Agua', recD: 'Permite que los taninos y la acidez de los frutos negros brillen.',
      alt: 'Leche de almendra', altD: 'La almendra suaviza la intensidad.',
    },
    allergens: { lacteos: false, gluten: false, huevo: false, frutosSecs: false, soja: false, sulfitos: true },
    allergenNotes: { sulfitos: 'Presentes en el vino y frutos negros procesados.' },
    baseType: 'agua',
    maridaje: ['Vino tinto suave', 'Café negro intenso'],
  },
  carda: {
    cls: 'th-carda', c: 'var(--carda)', c2: 'var(--carda2)',
    name: 'Cardamomo y Rosa', persona: 'La Elegancia Mística',
    desc: 'Posees una sensibilidad espiritual y una intuición aguda. Percibes dimensiones de la realidad que otros pasan por alto.',
    ins: {
      tag: 'TU ESENCIA',
      text: 'El cardamomo y la rosa han sido usados en rituales a lo largo de la historia humana. Tú tienes esa misma cualidad que eleva.',
      hl: 'Tu intuición no es magia. Es una forma muy afinada de escuchar.',
    },
    psych: 'William James describe la experiencia espiritual como una forma legítima de conocimiento que integra lo que la razón sola no puede alcanzar.',
    traits: [
      { l: 'INTUICIÓN', v: 'Muy aguda' },
      { l: 'ESPIRITUALIDAD', v: 'Propia' },
      { l: 'ELEGANCIA', v: 'Interior' },
      { l: 'PERCEPCIÓN', v: 'Extraordinaria' },
    ],
    tips: [
      { t: '<strong>Confía en lo que sientes</strong> aunque no puedas articularlo aún.' },
      { t: '<strong>Protege tu espacio sagrado.</strong>' },
      { t: '<strong>Comunica tu mundo interior.</strong>' },
      { t: '<strong>Ancla tu espiritualidad en lo cotidiano.</strong>' },
    ],
    base: {
      rec: 'Leche de almendra', recD: 'La almendra complementa el cardamomo y la rosa con suavidad.',
      alt: 'Leche entera', altD: 'Da más cuerpo al perfil floral.',
    },
    allergens: { lacteos: false, gluten: false, huevo: false, frutosSecs: true, soja: false, sulfitos: false },
    allergenNotes: { frutosSecs: 'Almendra si se usa como base.' },
    baseType: 'leche',
    maridaje: ['Té de cardamomo', 'Agua de rosas'],
  },
} as const satisfies Record<FlavorId, Flavor>;

// ════════ DUO DATA ════════
export const DUO_ALL: Record<FlavorId, string> = {
  fresa: 'La Alianza del Corazón',
  vainilla: 'La Alianza Serena',
  menta: 'La Alianza Brillante',
  choco: 'La Alianza Profunda',
  mango: 'La Alianza Solar',
  lavanda: 'La Alianza Poética',
  matcha: 'La Alianza Consciente',
  miel: 'La Alianza Reparadora',
  higo: 'La Alianza Evolucionada',
  caramelo: 'La Alianza Dinámica',
  yuzu: 'La Alianza Eléctrica',
  earl: 'La Alianza Intelectual',
  chai: 'La Alianza Especiada',
  platano: 'La Alianza Nostálgica',
  vino: 'La Alianza Madura',
  carda: 'La Alianza Mística',
} as const;

export const DUO_TIP: Record<FlavorId, string> = {
  fresa: 'Cuando la intensidad suba, acuerden una palabra que signifique "pausa, no abandono". Esa distinción cambia todo en vínculos como el de ustedes.',
  vainilla: 'Introduzcan pequeñas dosis de novedad deliberada. Su estabilidad es una fortaleza, no una limitación.',
  menta: 'Practiquen estar juntos sin analizar ni planear. El silencio compartido también es una forma de conexión.',
  choco: 'Busquen momentos de ligereza deliberada. Su profundidad no se pierde — de hecho, se enriquece.',
  mango: 'Reserven espacio para conversaciones difíciles. Los vínculos crecen cuando se sostienen las cosas que incomodan.',
  lavanda: 'Practiquen la comunicación verbal directa. No siempre el otro puede leer lo que no se dice.',
  matcha: 'Celebren el proceso, no solo el resultado. Su vínculo se fortalece cuando se permiten estar juntos también en lo imperfecto.',
  miel: 'Identifiquen quién cuida a quienes cuidan. Los vínculos nutritivos son aquellos donde el cuidado va en ambas direcciones.',
  higo: 'Permítanse cambiar juntos sin que eso amenace lo que han construido. Evolucionar de la mano requiere confianza.',
  caramelo: 'Celebren sus contradicciones como dúo. No necesitan ser iguales para ser compatibles — esa diferencia es su mayor fortaleza.',
  yuzu: 'Aprendan a aterrizar su energía compartida en proyectos concretos. Son un dúo que puede cambiar el ambiente de cualquier espacio.',
  earl: 'Practiquen la imprecisión ocasional. No todo momento compartido necesita ser analizado — algunos simplemente necesitan vivirse.',
  chai: 'Compartan su sabiduría con el mundo. Su vínculo tiene una calidez que otros necesitan — no la guarden solo para ustedes.',
  platano: 'Creen nuevos recuerdos con la misma atención con que cuidan los del pasado. Su historia es una base, no un destino.',
  vino: 'Permítanse también la ligereza. La intensidad que comparten es su fuerza — pero los mejores vínculos también saben cuándo reír.',
  carda: 'Compartan su sensibilidad espiritual con quienes los rodean. Hay algo en la forma en que se relacionan que eleva cualquier espacio.',
} as const;

// ════════ VINCULOS ════════
export const VINCULOS: Record<VinculoId, { icon: string; label: string }> = {
  pareja: { icon: '💑', label: 'Pareja' },
  amigos: { icon: '🫂', label: 'Amigos' },
  hermanos: { icon: '👫', label: 'Hermanos' },
  familia: { icon: '🏠', label: 'Familia' },
  colegas: { icon: '🤝', label: 'Colegas' },
  otro: { icon: '✨', label: 'Otro' },
} as const;

// ════════ FLAVOR EMOJI ════════
export const FLAVOR_EMOJI: Record<FlavorId, string> = {
  fresa: '🍓',
  vainilla: '🍦',
  menta: '🌿',
  choco: '🍫',
  mango: '🥭',
  lavanda: '💜',
  matcha: '🍵',
  miel: '🍯',
  higo: '🫐',
  caramelo: '🧁',
  yuzu: '🍋',
  earl: '☕',
  chai: '🌶',
  platano: '🍌',
  vino: '🍷',
  carda: '🌹',
} as const;

// ════════ AFFINITY MATRIX ════════
export const AFFINITY: Record<FlavorId, Record<FlavorId, number>> = {
  fresa:    { fresa: 95, vainilla: 72, menta: 65, choco: 78, mango: 88, lavanda: 82, matcha: 60, miel: 90, higo: 68, caramelo: 75, yuzu: 70, earl: 58, chai: 85, platano: 80, vino: 92, carda: 76 },
  vainilla: { fresa: 72, vainilla: 95, menta: 78, choco: 70, mango: 65, lavanda: 74, matcha: 85, miel: 80, higo: 82, caramelo: 68, yuzu: 60, earl: 88, chai: 76, platano: 86, vino: 64, carda: 70 },
  menta:    { fresa: 65, vainilla: 78, menta: 95, choco: 72, mango: 80, lavanda: 68, matcha: 82, miel: 62, higo: 66, caramelo: 70, yuzu: 90, earl: 85, chai: 60, platano: 58, vino: 64, carda: 62 },
  choco:    { fresa: 78, vainilla: 70, menta: 72, choco: 95, mango: 68, lavanda: 74, matcha: 76, miel: 72, higo: 80, caramelo: 82, yuzu: 62, earl: 78, chai: 75, platano: 72, vino: 88, carda: 80 },
  mango:    { fresa: 88, vainilla: 65, menta: 80, choco: 68, mango: 95, lavanda: 70, matcha: 64, miel: 85, higo: 60, caramelo: 86, yuzu: 92, earl: 62, chai: 78, platano: 74, vino: 66, carda: 68 },
  lavanda:  { fresa: 82, vainilla: 74, menta: 68, choco: 74, mango: 70, lavanda: 95, matcha: 78, miel: 76, higo: 72, caramelo: 66, yuzu: 74, earl: 80, chai: 70, platano: 68, vino: 76, carda: 92 },
  matcha:   { fresa: 60, vainilla: 85, menta: 82, choco: 76, mango: 64, lavanda: 78, matcha: 95, miel: 70, higo: 80, caramelo: 72, yuzu: 82, earl: 88, chai: 68, platano: 72, vino: 66, carda: 74 },
  miel:     { fresa: 90, vainilla: 80, menta: 62, choco: 72, mango: 85, lavanda: 76, matcha: 70, miel: 95, higo: 78, caramelo: 74, yuzu: 68, earl: 65, chai: 92, platano: 86, vino: 70, carda: 72 },
  higo:     { fresa: 68, vainilla: 82, menta: 66, choco: 80, mango: 60, lavanda: 72, matcha: 80, miel: 78, higo: 95, caramelo: 70, yuzu: 60, earl: 82, chai: 80, platano: 88, vino: 76, carda: 74 },
  caramelo: { fresa: 75, vainilla: 68, menta: 70, choco: 82, mango: 86, lavanda: 66, matcha: 72, miel: 74, higo: 70, caramelo: 95, yuzu: 84, earl: 68, chai: 72, platano: 70, vino: 80, carda: 64 },
  yuzu:     { fresa: 70, vainilla: 60, menta: 90, choco: 62, mango: 92, lavanda: 74, matcha: 82, miel: 68, higo: 60, caramelo: 84, yuzu: 95, earl: 78, chai: 64, platano: 58, vino: 62, carda: 70 },
  earl:     { fresa: 58, vainilla: 88, menta: 85, choco: 78, mango: 62, lavanda: 80, matcha: 88, miel: 65, higo: 82, caramelo: 68, yuzu: 78, earl: 95, chai: 70, platano: 74, vino: 72, carda: 78 },
  chai:     { fresa: 85, vainilla: 76, menta: 60, choco: 75, mango: 78, lavanda: 70, matcha: 68, miel: 92, higo: 80, caramelo: 72, yuzu: 64, earl: 70, chai: 95, platano: 88, vino: 74, carda: 80 },
  platano:  { fresa: 80, vainilla: 86, menta: 58, choco: 72, mango: 74, lavanda: 68, matcha: 72, miel: 86, higo: 88, caramelo: 70, yuzu: 58, earl: 74, chai: 88, platano: 95, vino: 70, carda: 68 },
  vino:     { fresa: 92, vainilla: 64, menta: 64, choco: 88, mango: 66, lavanda: 76, matcha: 66, miel: 70, higo: 76, caramelo: 80, yuzu: 62, earl: 72, chai: 74, platano: 70, vino: 95, carda: 82 },
  carda:    { fresa: 76, vainilla: 70, menta: 62, choco: 80, mango: 68, lavanda: 92, matcha: 74, miel: 72, higo: 74, caramelo: 64, yuzu: 70, earl: 78, chai: 80, platano: 68, vino: 82, carda: 95 },
} as const;

// ════════ MARIDAJE ════════
export const MARIDAJE: Record<FlavorId, string[]> = {
  fresa:    ['Espresso doble', 'Agua con gas y lima'],
  vainilla: ['Café de olla', 'Té chai caliente'],
  menta:    ['Agua mineral fría', 'Té verde con hielo'],
  choco:    ['Café negro', 'Mezcal añejo'],
  mango:    ['Agua de jamaica', 'Kombucha de jengibre'],
  lavanda:  ['Té de camomila', 'Agua floral de rosas'],
  matcha:   ['Agua de coco', 'Té verde ceremonial'],
  miel:     ['Té de canela', 'Agua tibia con limón'],
  higo:     ['Vino blanco seco', 'Café de filtro'],
  caramelo: ['Cappuccino', 'Sidra natural'],
  yuzu:     ['Agua tónica', 'Té cítrico frío'],
  earl:     ['Earl Grey caliente', 'Agua mineral con ralladura'],
  chai:     ['Chai latte', 'Café con especias'],
  platano:  ['Leche con chocolate', 'Café con leche'],
  vino:     ['Vino tinto suave', 'Café negro intenso'],
  carda:    ['Té de cardamomo', 'Agua de rosas'],
} as const;

// ════════ TEMPORADA ════════
export const TEMPORADA: Set<FlavorId> = new Set<FlavorId>(['yuzu', 'carda', 'higo']);

// ════════ ALLERGEN METADATA ════════
export const AL_META: Array<{ key: keyof FlavorAllergens; label: string }> = [
  { key: 'lacteos',    label: 'Lácteos' },
  { key: 'gluten',     label: 'Gluten' },
  { key: 'huevo',      label: 'Huevo' },
  { key: 'frutosSecs', label: 'Frutos secos' },
  { key: 'soja',       label: 'Soja' },
  { key: 'sulfitos',   label: 'Sulfitos' },
] as const;
