import type { QuizQuestion } from "@/types";

export const QP: QuizQuestion[] = [
  {q:"¿Cómo prefieres pasar tu tiempo libre?",o:[{t:"Con personas que me llenen de energía",s:{fresa:3,miel:1}},{t:"En calma, sin mucho estímulo externo",s:{vainilla:3,matcha:1}},{t:"Explorando algo nuevo — un lugar o una idea",s:{menta:3,yuzu:1}},{t:"A solas con mis pensamientos",s:{choco:3,earl:1}},{t:"En una aventura espontánea sin plan",s:{mango:3}},{t:"Creando algo — arte, escritura o música",s:{lavanda:3,carda:1}},{t:"Con un ritual consciente — meditación, lectura",s:{matcha:3}},{t:"Cocinando o recibiendo a personas queridas",s:{chai:3,platano:1}}]},
  {q:"¿Cómo describes tu forma de comunicarte?",o:[{t:"Directo/a y emocional — expreso lo que siento",s:{fresa:3,vino:1}},{t:"Calmado/a y reflexivo/a — pienso antes de hablar",s:{vainilla:3,earl:1}},{t:"Rápido/a y lleno/a de ideas",s:{menta:3,yuzu:1}},{t:"Profundo/a — prefiero conversaciones con peso",s:{choco:3}},{t:"Alegre y espontáneo/a",s:{mango:3}},{t:"Cálido/a — hago que la gente se sienta bienvenida",s:{chai:3,miel:1}},{t:"Sutil, con capas — no digo todo de frente",s:{carda:3,lavanda:1}},{t:"Muy preciso/a — cuido mucho las palabras",s:{earl:3,matcha:1}}]},
  {q:"Cuando algo difícil sucede, tu primer impulso es...",o:[{t:"Buscar a alguien con quien hablarlo",s:{fresa:3,miel:1}},{t:"Esperar con calma a que la situación se aclare",s:{vainilla:3}},{t:"Analizar qué pasó y buscar una solución",s:{menta:3,earl:1}},{t:"Procesarlo internamente, a veces durante días",s:{choco:3}},{t:"Moverme — la acción me ayuda a salir del loop",s:{mango:3,yuzu:1}},{t:"Crear algo o escuchar música para procesar",s:{lavanda:3,carda:1}},{t:"Recurrir a una rutina que me ancle",s:{matcha:3}},{t:"Buscar el aprendizaje en lo sucedido",s:{higo:3,chai:1}}]},
  {q:"¿Qué valoras más en una relación cercana?",o:[{t:"La intensidad y la conexión emocional real",s:{fresa:3,vino:1}},{t:"La estabilidad y la confianza sostenida",s:{vainilla:3,platano:1}},{t:"Las conversaciones que me hacen crecer",s:{menta:3,earl:1}},{t:"La profundidad — pocos pero genuinos",s:{choco:3}},{t:"La diversión y los buenos momentos",s:{mango:3}},{t:"Ser entendido/a sin tener que explicarlo todo",s:{lavanda:3,carda:1}},{t:"La lealtad y la memoria compartida",s:{platano:3,higo:1}},{t:"La calidez — sentirme bienvenido/a siempre",s:{chai:3,miel:1}}]},
  {q:"¿Cuál es tu mayor fortaleza?",o:[{t:"Mi capacidad de empatizar y conectar",s:{fresa:3,miel:1}},{t:"Mi calma — no entro en pánico fácilmente",s:{vainilla:3,matcha:1}},{t:"Analizo rápido y encuentro soluciones efectivas",s:{menta:3,earl:1}},{t:"Mi profundidad — proceso con mucho cuidado",s:{choco:3}},{t:"Mi resiliencia — me recupero con rapidez",s:{mango:3,caramelo:1}},{t:"Mi intuición — siento qué camino tomar",s:{lavanda:3,carda:1}},{t:"Mi disciplina y mi capacidad de mantener el foco",s:{matcha:3}},{t:"Mi capacidad de sostener lo que otros no pueden",s:{miel:3,chai:1}}]},
  {q:"¿Cómo describes tu relación con el pasado?",o:[{t:"Tengo mucho afecto por mis recuerdos",s:{fresa:3,platano:1}},{t:"Lo proceso con calma y lo uso como aprendizaje",s:{vainilla:3}},{t:"Aprendo de él y sigo — no me quedo ahí",s:{menta:3,yuzu:1}},{t:"Lo cargo de forma profunda — me forma",s:{choco:3,vino:1}},{t:"No me quedo en él — prefiero el presente",s:{mango:3}},{t:"Lo integro de forma intuitiva y simbólica",s:{carda:3,lavanda:1}},{t:"Lo honro pero no me limita — evoluciono",s:{higo:3,matcha:1}},{t:"Es mi fuente de identidad y de fuerza",s:{platano:3,chai:1}}]},
  {q:"¿Qué entorno te hace sentir más tú mismo/a?",o:[{t:"Lleno de personas que quiero cerca",s:{fresa:3}},{t:"Ordenado y tranquilo, sin estímulos de más",s:{vainilla:3,earl:1}},{t:"Con algo interesante en que pensar",s:{menta:3,matcha:1}},{t:"Silencioso, que invite a reflexionar",s:{choco:3}},{t:"Dinámico y colorido, en constante movimiento",s:{mango:3,yuzu:1}},{t:"Lleno de detalles estéticos pensados",s:{lavanda:3,carda:1}},{t:"Con historia — lugares con carácter y tradición",s:{higo:3,platano:1}},{t:"Cálido — donde pueda compartir la mesa",s:{chai:3,miel:1}}]},
  {q:"¿Cómo manifiestas que alguien te importa?",o:[{t:"Con palabras — digo directamente lo que siento",s:{fresa:3}},{t:"Con actos consistentes y presencia sostenida",s:{vainilla:3,platano:1}},{t:"Compartiendo cosas que les hacen crecer",s:{menta:3}},{t:"Con conversaciones profundas y atención total",s:{choco:3,vino:1}},{t:"Con planes espontáneos y momentos memorables",s:{mango:3,yuzu:1}},{t:"Con detalles muy pequeños y pensados",s:{lavanda:3,carda:1}},{t:"Cuidándoles — preparando algo concreto",s:{miel:3,chai:1}},{t:"Siendo leal en los momentos difíciles",s:{platano:3,higo:1}}]},
  {q:"¿Qué tipo de narrativas te atrapan más?",o:[{t:"Historias de amor y vínculo humano profundo",s:{fresa:3,vino:1}},{t:"Narrativas tranquilas y bien escritas",s:{vainilla:3,earl:1}},{t:"Ciencia ficción, misterio, ideas grandes",s:{menta:3,yuzu:1}},{t:"Dramas psicológicos o filosóficos",s:{choco:3}},{t:"Aventuras con personajes carismáticos",s:{mango:3}},{t:"Arte, poesía y narrativa sensorial",s:{lavanda:3,carda:1}},{t:"Épicas o históricas — lo que conecta pasado y presente",s:{higo:3,chai:1}},{t:"Historias de transformación y consciencia",s:{matcha:3,earl:1}}]},
  {q:"¿Cuál es tu mayor miedo?",o:[{t:"Perder a las personas que amo",s:{fresa:3,miel:1}},{t:"El caos o perder el control",s:{vainilla:3,matcha:1}},{t:"Quedarme estancado/a sin crecer",s:{menta:3,yuzu:1}},{t:"No llegar a entenderme completamente",s:{choco:3}},{t:"Perderme experiencias importantes",s:{mango:3}},{t:"No poder expresar lo que siento",s:{lavanda:3,carda:1}},{t:"No ser fiel a mis valores o mis raíces",s:{higo:3,platano:1}},{t:"Perder la intensidad o la profundidad con el tiempo",s:{vino:3,choco:1}}]},
  {q:"¿Cómo te describes en momentos de presión?",o:[{t:"Busco apoyo — no me gusta procesarlo solo/a",s:{fresa:3,miel:1}},{t:"Busco calma — el ruido me desorienta",s:{vainilla:3,matcha:1}},{t:"Me activo — la presión me hace pensar más rápido",s:{menta:3,yuzu:1}},{t:"Me profundizo — necesito entender antes de actuar",s:{choco:3,earl:1}},{t:"Me muevo — la acción física me regula",s:{mango:3}},{t:"Me apoyo en mis rutinas — el orden me sostiene",s:{matcha:3}},{t:"Recurro a lo conocido — lo familiar me da fuerza",s:{platano:3,higo:1}},{t:"Necesito un espacio de belleza o silencio",s:{lavanda:3,carda:1}}]},
  {q:"¿Qué te motiva más profundamente?",o:[{t:"Las personas y las conexiones que construyo",s:{fresa:3,miel:1}},{t:"La estabilidad y el bienestar a largo plazo",s:{vainilla:3}},{t:"El conocimiento y el crecimiento intelectual",s:{menta:3,earl:1}},{t:"Entenderme a mí mismo/a y entender el mundo",s:{choco:3,vino:1}},{t:"Vivir experiencias que valgan la pena",s:{mango:3,yuzu:1}},{t:"La belleza, la expresión y lo que me hace sentir",s:{lavanda:3,carda:1}},{t:"El equilibrio y vivir con intención",s:{matcha:3}},{t:"Dejar algo duradero para quienes vengan",s:{higo:3,platano:1}}]},
  {q:"¿Cómo quieres que te recuerden?",o:[{t:"Como alguien que amó profundo y sin miedo",s:{fresa:3,vino:1}},{t:"Como alguien que siempre estuvo cuando se necesitaba",s:{vainilla:3,platano:1}},{t:"Como alguien que cambió la forma de pensar de otros",s:{menta:3,yuzu:1}},{t:"Como alguien que dejó algo verdadero y profundo",s:{choco:3}},{t:"Como alguien que hizo la vida más alegre",s:{mango:3}},{t:"Como alguien que hacía sentir la belleza del mundo",s:{lavanda:3,carda:1}},{t:"Como alguien que cuidó con una calidez genuina",s:{miel:3,chai:1}},{t:"Como alguien que no se parecía a nadie más",s:{yuzu:3,caramelo:1}}]}
];

export const QT: QuizQuestion[] = [
  {q:"¿Cómo describirías tu energía en este momento?",o:[{t:"Llena, me siento bien y con ganas",s:{mango:3,fresa:1}},{t:"Tranquila, en un buen equilibrio",s:{vainilla:3,matcha:1}},{t:"Curiosa, con muchas cosas en la mente",s:{menta:3,earl:1}},{t:"Profunda, procesando algo importante",s:{choco:3,vino:1}},{t:"Cansada, necesito ser cuidada",s:{miel:3,platano:1}},{t:"Creativa, con ganas de expresar algo",s:{lavanda:3,yuzu:1}},{t:"Nostálgica, con el corazón en el pasado",s:{platano:3,chai:1}},{t:"Mística, conectada con algo más grande",s:{carda:3,lavanda:1}}]},
  {q:"¿Qué necesitas más ahora mismo?",o:[{t:"Conexión — alguien con quien compartir",s:{fresa:3,miel:1}},{t:"Quietud — silencio y espacio para mí",s:{vainilla:3,matcha:1}},{t:"Estimulación — algo que encienda mi mente",s:{menta:3,yuzu:1}},{t:"Profundidad — una conversación de verdad",s:{choco:3,earl:1}},{t:"Alegría — algo ligero y divertido",s:{mango:3}},{t:"Belleza — algo que me haga sentir",s:{lavanda:3,carda:1}},{t:"Confort — algo conocido que me abrace",s:{chai:3,platano:1}},{t:"Energía — algo que me despierte",s:{miel:3,yuzu:1}}]},
  {q:"Si tu estado de ánimo fuera un color, sería...",o:[{t:"Rojo — intenso y apasionado",s:{fresa:3,vino:1}},{t:"Beige cálido — sereno y equilibrado",s:{vainilla:3}},{t:"Verde brillante — fresco y activo",s:{menta:3,matcha:1}},{t:"Negro profundo — complejo y reflexivo",s:{choco:3}},{t:"Naranja — vibrante y lleno de vida",s:{mango:3,yuzu:1}},{t:"Lila suave — soñador y sensible",s:{lavanda:3,carda:1}},{t:"Dorado — cálido y con historia",s:{chai:3,platano:1}},{t:"Azul profundo — sereno pero intenso",s:{earl:3,vino:1}}]},
  {q:"¿Qué tipo de espacio te hace sentir bien hoy?",o:[{t:"Uno lleno de personas y movimiento",s:{fresa:3,mango:1}},{t:"Uno tranquilo, ordenado y sin ruido",s:{vainilla:3,earl:1}},{t:"Una cafetería con buena conversación",s:{menta:3,chai:1}},{t:"Uno íntimo y silencioso para pensar",s:{choco:3}},{t:"Afuera — luz, cielo, naturaleza",s:{mango:3,yuzu:1}},{t:"Uno lleno de arte o música",s:{lavanda:3,carda:1}},{t:"La casa de alguien que quiero",s:{platano:3,miel:1}},{t:"Uno con incienso, velas, calma ritual",s:{carda:3,matcha:1}}]},
  {q:"¿Qué tipo de sabor se antoja más ahora?",o:[{t:"Algo dulce y frutal — refrescante",s:{fresa:3,mango:1}},{t:"Algo suave y delicado — sin sobresaltos",s:{vainilla:3}},{t:"Algo fresco y con punch — que despierte",s:{menta:3,yuzu:1}},{t:"Algo intenso y complejo — con capas",s:{choco:3,vino:1}},{t:"Algo tropical y vibrante — veraniego",s:{mango:3}},{t:"Algo floral y sutil — que eleve",s:{lavanda:3,carda:1}},{t:"Algo cálido y reconfortante — especiado",s:{chai:3,miel:1}},{t:"Algo nostálgico — un sabor de siempre",s:{platano:3,higo:1}}]},
  {q:"¿Cuál es el pensamiento que más se repite hoy?",o:[{t:"Extraño a alguien o quiero estar con alguien",s:{fresa:3,platano:1}},{t:"Necesito un momento de calma real",s:{vainilla:3,matcha:1}},{t:"Hay algo que quiero entender o resolver",s:{menta:3,earl:1}},{t:"Estoy procesando algo que no termino de digerir",s:{choco:3,vino:1}},{t:"Quiero hacer algo espontáneo y diferente",s:{mango:3,yuzu:1}},{t:"Siento algo que no sé cómo nombrarlo",s:{lavanda:3,carda:1}},{t:"Necesito que alguien me cuide hoy",s:{miel:3,chai:1}},{t:"Estoy pensando en el pasado o en alguien de antes",s:{platano:3,higo:1}}]},
  {q:"Si hoy fuera una canción, sería...",o:[{t:"Una canción de amor intensa",s:{fresa:3,vino:1}},{t:"Un piano lento y tranquilo",s:{vainilla:3,earl:1}},{t:"Algo indie con letras interesantes",s:{menta:3,yuzu:1}},{t:"Jazz oscuro y complejo",s:{choco:3}},{t:"Pop tropical lleno de energía",s:{mango:3}},{t:"Una melodía etérea y envolvente",s:{lavanda:3,carda:1}},{t:"Música de fondo de una tarde con té",s:{chai:3,platano:1}},{t:"Una canción de los que ya no están",s:{platano:3,vino:1}}]},
  {q:"¿Cómo quieres que termine este día?",o:[{t:"Con alguien que quiero, compartiendo",s:{fresa:3,miel:1}},{t:"En silencio total — solo yo",s:{vainilla:3,matcha:1}},{t:"Habiendo aprendido algo nuevo",s:{menta:3,earl:1}},{t:"Con una conversación profunda",s:{choco:3}},{t:"Cansado/a pero con una sonrisa",s:{mango:3,yuzu:1}},{t:"Habiendo creado o expresado algo",s:{lavanda:3,carda:1}},{t:"Con algo rico, caliente y tranquilo",s:{chai:3,platano:1}},{t:"En un espacio de calma y consciencia",s:{carda:3,matcha:1}}]},
  {q:"Una sola palabra para describir cómo te sientes hoy:",o:[{t:"Conectado/a",s:{fresa:3}},{t:"Tranquilo/a",s:{vainilla:3,matcha:1}},{t:"Curioso/a",s:{menta:3}},{t:"Reflexivo/a",s:{choco:3,earl:1}},{t:"Energético/a",s:{mango:3,yuzu:1}},{t:"Sensible",s:{lavanda:3,carda:1}},{t:"Nostálgico/a",s:{platano:3,chai:1}},{t:"Intenso/a",s:{vino:3,fresa:1}}]}
];
